### ISSUE TITLE
BAT test virtual guest creation timeout issue

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry-incubator/bosh-softlayer-cpi-release#1]
When I tried to run 1 BAT test case (the ssh to the vm one), BAT test case tried to use the softlayer external CPI to create a virtual guest, but the created virtual guest in softlayer remains at the pending transaction status, which will cause the BAT test case time out failure, here I paste a screenshot for the console output of the failure

![2014-11-05 10 41 14](https://cloud.githubusercontent.com/assets/5344440/4919406/407dc776-64fa-11e4-9d12-cff9360a9868.png)

**Comment by maximilien** [comment]
@xingzhou, thanks for opening this. So I expected timeout but not the error waiting for transaction. Can you please pull and try this again and let me know if you are seeing same error. Or if you have already, then confirm and I will look into it. Thanks.

**Comment by xingzhou** [comment]
@maximilien, I tried the same test case twice with the latest bosh code today, today I got a ping time out error, while executing the test case, I can see that today, the vm can be created successfully in the softlayer without any pending transacations any more, but the ping operation performed by bosh is timeout. here I attach the new error screenshot. The vm can be automatically deleted after the bat exit.

I'm trying to add some more output from the CPI side now.

![2014-11-06 2 52 42](https://cloud.githubusercontent.com/assets/5344440/4931937/984225b0-6581-11e4-86eb-1f685a241e8f.png)

**Comment by xingzhou** [comment]
This ping issue remained there after I change the datacenter to amsterdam, this time, the compilation virtual machine and the bosh server vm are in the same data center, need to figure out whether bosh is using a wrong IP address from the CPI

**Comment by maximilien** [comment]
Yes, this is correct behavior that I expected. The timeout has to do with the agent not configured correctly to talk back to Director who will timeout the deployment after 10 minutes. The director should clean up and delete the VM.

I am working on this and will update once I have a fix.

**Comment by maximilien** [comment]
Closing this as well since @karafelix got most of this to work now on the pipeline.

Reopen if needed.
