### ISSUE TITLE
Move release into the CPI project

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry-incubator/bosh-softlayer-cpi-release#14]
/cc @karafelix as per our discussion

**Comment by maximilien** [comment]
@jianqiu let's discuss this. It would make the whole process of release creation (being updated to latest CPI code) easier.

**Comment by jianqiu** [comment]
@maximilien  We had come to an agreement, keep bosh-softlayer-cpi as submodule bosh-softlayer-cpi-release project, so closing it.

**Comment by maximilien** [comment]
Cool, thanks
