### ISSUE TITLE
Where can i get bosh stemcell for softlayer?.

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry-incubator/bosh-softlayer-cpi-release#17]
Hello.

I am trying to deploy bosh on Softlayer using bosh-init.
https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/blob/master/docs/bosh-init-usage.md

Where can i get bosh stemcell for softlayer?.
file://./light-bosh-stemcell-3031-softlayer-esxi-ubuntu-trusty-go_agent.tgz

**Comment by jianqiu** [comment]
Please read the release nodes, I had already updated the delivery.
