### ISSUE TITLE
The release structure for bosh-micro-cli is different than current release structure

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry-incubator/bosh-softlayer-cpi-release#2]
In bosh-micro-cli project, we are using a different release structure than current one. e.g.:
1. in bosh-micro-cli release, release.MF is located together with packages & src folder
2. in bosh-micro-cli release, jobs/xx/spec shall be renamed to job.MF
3. in bosh-micro-cli release, each job under jobs folder shall be compressed into .tgz format, the same for all the packages under packages folder

so based on the above changes, need to do some changes to current release for bosh-micro-cli?

**Comment by maximilien** [comment]
Closing this since @jianqiu got bosh-init to work with the eCPI release.

Please reopen if this is still a valid issue.

/cc @karafelix
