### ISSUE TITLE
Deployments should not require powerdns

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry-incubator/bosh-softlayer-cpi-release#21]
Let me use a concrete example to highlight this issue.
The latest release of Concourse uses links. The generated config ends up with generated hostnames requiring powerdns as a DNS entry.

Golang based programs will stop DNS resolution when PowerDNS reports a not found. I have reported this issue and it will be fixed in Go 1.7.
What this means is that when you are using Concourse, any internet URL, e.g., docker images, github urls, etc... cannot be resolved.
My solution was to removed PowerDNS from the DNS list, and modify the generated config to use private ips or localhost where possible which allowed concourse to function properly.

It also didn't make sense that PowerDNS resolved hostname to the public IP rather than the private IP.

**Comment by flintstonecf** [comment]
@maximilien 
+1 to this issue. It would be very important to get that fixed, i.e. returning proper IP addresses (probably private IPs). We'd like to create a cf-release template for SL, but with this is impossible to accomplish.

**Comment by maximilien** [comment]
We are working on a solution for BOSH agent and BOSH that gets rid of pDNS. It is in the works.

**Comment by maximilien** [comment]
Track all DNS stories [here](https://www.pivotaltracker.com/n/projects/956238) on BOSH tracker and looking at `synced_dns` epic or seach for stories using `dns` tag

**Comment by maximilien** [comment]
I closing this since the BOSH DNS track is moving along. Please monitor that for future release that will resolve your main concern.
