### ISSUE TITLE
Release structure is inconsistent with other golang based projects in Cloud Foundry

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry-incubator/bosh-softlayer-cpi-release#22]
The release tree includes an `.envrc` file in the root of the release that explicitly sets the GOPATH to the base directory of the release. Unfortunately, the only code in the release is in a submodule path that does not include the necessary `github.com/cloudfoundry` parent directories.  This breaks tooling that understands the `GOPATH`.

If the repository is supposed to be treated as a `GOPATH`, you need to put the submodule in the correct path.

**Comment by jianqiu** [comment]
@sykesm 
Thanks for your insight, we are considering to refine the release structure.

**Comment by maximilien** [comment]
@sykesm note that this repo will be deleted as we migrate to one repo for the code and release. This will be done in v2 timeframe.

After we merge, please verify we have addressed your concern.

/cc @jianqiu
