### ISSUE TITLE
Unable to bosh ssh to other VMs

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry-incubator/bosh-softlayer-cpi-release#29]
Steps to reproduce:

bosh login <directorURL>
bosh download manifest <deployment-name> /tmp/manifest.yml
bosh deployment /tmp/manifest.yml
bosh ssh <job_name> <instance_id>

I get the following output in my test ...
``
Acting as user 'admin' on deployment 'flintstone-hkg02-diego' on 'bosh'
Target deployment is`flintstone-hkg02-diego'

Setting up ssh artifacts

Director task 565

Task 565 done
Starting interactive shell on job database_z1/0
ssh: connect to host 161.202.52.50 port 22: Operation timed out

Cleaning up ssh artifacts

Director task 566

Task 566 done
``
This now just hangs there indefinitely and does not connect to the VM.

I have not tried the options --gateway_host --gateway_user --gateway_identity_file as The connection to the director seems to work but the further connection is failing.

At the moment we are required to use the bosh director VM as a jump box.  Logging into the bosh director and then logging into the VMs from there.  But the bosh ssh should be able to tunnel through.

**Comment by maximilien** [comment]
Moving this issue to `bosh-softlayer-cpi` repo as issue [#138](https://github.com/cloudfoundry/bosh-softlayer-cpi/issues/138), and closing this one.
