### ISSUE TITLE
bosh-micro-cli uses a different working directory than the one defined in the packages/cpi/packaging script

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry-incubator/bosh-softlayer-cpi-release#3]
We tried bosh-micro-cli, seems when compiling SL eCPI, the working directory is under packages folder, so this line in packages/cpi/packaging script will lead to error:

`mv bosh-softlayer-cpi go/src/github.com/maximilien/`

we tried to change it into:

`mv ../../src/bosh-softlayer-cpi go/src/github.com/maximilien/`

and then bosh-micro-cli is happy

**Comment by maximilien** [comment]
Closing this since @jianqui got bosh-init to work with the eCPI code.

Please reopen if this is still an issue after JQ's updates are merged.

/cc @karafelix
