### ISSUE TITLE
Submodule commit is not available

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry-incubator/bosh-softlayer-cpi-release#44]
After cloning the release, I attempted to retrieve the submodules for a build but it failed:

```
$ git submodule update --init --recursive
error: no such remote ref b38017729f53bd58283591cfd49329225b075953
Fetched in submodule path 'src/github.com/cloudfoundry/bosh-softlayer-cpi', but it did not contain b38017729f53bd58283591cfd49329225b075953. Direct fetching of that commit failed.
```

**Comment by mattcui** [comment]
@sykesm We are moving to [bosh-softlayer-cpi](https://github.com/cloudfoundry/bosh-softlayer-cpi), this repo will be deleted (or archived) once we complete the merge into [bosh-softlayer-cpi](https://github.com/cloudfoundry/bosh-softlayer-cpi). Currently, @maximilien is reviewing all changes in [develop_v4](https://github.com/cloudfoundry/bosh-softlayer-cpi/tree/develop_v4), he will complete the merge soon.

**Comment by maximilien** [comment]
Yup, I am still reviewing. Should be done by the scrum call tonight.
