### ISSUE TITLE
need build-dawin-amd64 script when compiling the eCPI on Mac OS

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry-incubator/bosh-softlayer-cpi-release#5]
May need a new bin/build-dawin-amd64 script when compiling the eCPI on Mac OS, this script is similar to bin/build-linux-amd64

**Comment by maximilien** [comment]
I am closing this since the eCPI release should only be for Linux. We are not supporting Mac OS X, though, you should still be able to test on a Mac OS X development machine.

/cc @karafelix @jianqiu
